# Generated by Django 2.2.4 on 2019-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
