# Generated by Django 2.2.4 on 2019-11-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20191112_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
