# Generated by Django 2.2.4 on 2019-08-19 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('score_mode', models.CharField(max_length=10)),
                ('score_parameter', models.IntegerField(default=None)),
                ('time_limit', models.FloatField(default=1)),
                ('memory_limit', models.IntegerField(default=256)),
                ('diff_mode', models.CharField(max_length=10)),
                ('custom_grader', models.CharField(default=None, max_length=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('tags', models.ManyToManyField(to='tasks.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('input', models.FileField(upload_to='')),
                ('output', models.FileField(upload_to='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
    ]
